### ISSUE TITLE
Calendar sync: Fatal error

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#33]
Hi there,

I just updated to the newest version and now I get this error message if I enable the calendar sync:
```
Error: Call to a member function adjust() on null (0)
#0 /var/www/xxxxxxx/applications/membermap/sources/Map/Map.php(380): IPS\membermap\extensions\membermap\Mapmarkers\_Calendar->getLocations()
#1 /var/www/xxxxxxx/applications/membermap/sources/Map/Map.php(237): IPS\membermap\_Map->recacheJsonFile()
#2 /var/www/xxxxxxx/applications/membermap/modules/front/membermap/showmap.php(47): IPS\membermap\_Map->checkForCache()
#3 /var/www/xxxxxxx/system/Dispatcher/Controller.php(96): IPS\membermap\modules\front\membermap\_showmap->manage()
#4 /var/www/xxxxxxx/applications/membermap/modules/front/membermap/showmap.php(34): IPS\Dispatcher\_Controller->execute()
#5 /var/www/xxxxxxx/system/Dispatcher/Dispatcher.php(129): IPS\membermap\modules\front\membermap\_showmap->execute()
#6 /var/www/xxxxxxx/index.php(13): IPS\_Dispatcher->run()
#7 {main}
```

**Comment by Admonstrator** [comment]
Works fine now, many thanks! 👍
